/* generated by comp.py */
#include <stdio.h>
#include "vmewrap.h"
#include "lexan.h"
#include "vmeaistd.h"

char BoardName[]="VME2FPGA";
char BoardBaseAddress[11]="0x0";
char BoardSpaceLength[11]="0x1000";
char BoardSpaceAddmod[11]="A24";
char MonitLoad_usagehelp[]=" Graphical interface to MonitorLoad. Measure FPGA signals 'Ntimes' waiting\n\
 before measurement 'Tscale' times in arbitrary units, so Tscale should be \n\
 set up by set and try. Time interval between measurements is estimated\n\
 as (Time after measurement - time at start)/Ntimes. \n\
";

char GetStatusFPGA_usagehelp[]="\n\
Get Status of FPGA. \n\
\n\
";

Tpardesc MonitorLoad_parameters[2]={
{"Ntimes", 1},
{"Tscale", 1}};
char MonitorLoad_usagehelp[]="\n\
  C code to MonitLoad. Can be called also indepedently.\n\
  It loads FPGA and monitor signals without outputing them,\n\
  which leads to maximum time information.\n\
 ";

char LoadFPGA_usagehelp[]="\n\
Loads FPGA from Flash memory\n\
\n\
";

Tpardesc MonitorStatusFPGA_parameters[2]={
{"Ntimes", 1},
{"Tinterval", 1}};
char MonitorStatusFPGA_usagehelp[]="\n\
 Monitors FPGA by reading status word.\n\
 Ntimes: number of times you want to read status word.\n\
 Tinterval: time interval between reading status word in microseconds. \n\
\n\
";

char MonitorChange_usagehelp[]="\n\
 Loops infinitelly reading status and detect change\n\
 ";

char GetStatusFM_usagehelp[]="\n\
Get Status of Flash memory.\n\
";

char ResetFM_usagehelp[]="\n\
Resets Flash Memory.\n\
";

char LoadFM_usagehelp[]="\n\
Loads Flash Memory from the file on disk.\n\
";

char ReadInputFile_usagehelp[]="\n\
Reads the input configuration file from disk\n\
and saves it to array.\n\
";

char CheckContent_usagehelp[]="\n\
Reads Content of Flash Memory and compares it\n\
with the file on disk.\n\
";

char EraseFM_usagehelp[]="\n\
Erases Flash Memory.\n\
";

char Check1_usagehelp[]="Check against 1\n\
";

Tpardesc WriteFM_parameters[2]={
{"address", 2},
{"word", 2}};
char WriteFM_usagehelp[]="write to FM at address address.\n\
";

Tpardesc ReadFM_parameters[2]={
{"address", 2},
{"INCR", 1}};
char ReadFM_usagehelp[]="INCR=1 - read from address drom actual address\n\
INCR=0 - read address\n\
";

Tpardesc LoadFM0_parameters[3]={
{"pat", 1},
{"Nwords", 1},
{"file", 1}};
char LoadFM0_usagehelp[]="Writing pattern pat.\n\
pat>0xff : pat goes from 0 to 255 in cycle.\n\
file = 1 - read from config file\n\
file = 0 - uses generated pattern\n\
";

Tpardesc LoadFMErr_parameters[3]={
{"pat", 1},
{"Nwords", 1},
{"file", 1}};
char LoadFMErr_usagehelp[]="Writing pattern pat.\n\
pat>0xff : pat goes from 0 to 255 in cycle.\n\
file = 1 - read from config file\n\
file = 0 - uses generated pattern\n\
Different way of writing to FM:\n\
 I do not increase at last step.\n\
 I do increase with reset.\n\
";

char Correct_usagehelp[]="  Correct errors stored in AddErr and DatErr.\n\
";

Tpardesc LoadFMUB_parameters[2]={
{"pat", 1},
{"Nwords", 1}};
char LoadFMUB_usagehelp[]="Uses the Unlock Bypass Mode\n\
";

Tpardesc Check0_parameters[1]={
{"Nwords", 1}};
char Check0_usagehelp[]="Check against 0 or what is written in LoadFM0.\n\
";

Tpardesc Monitor_parameters[1]={
{"Ntimes", 1}};
char Monitor_usagehelp[]="Monitars data lines after write or read\n\
";

Tpardesc VMEwrite_parameters[3]={
{"Pedjaddress", 2},
{"Ntimes", 1},
{"word", 2}};
char VMEwrite_usagehelp[]="Large number of readings\n\
";

Tpardesc ReadLoop_parameters[1]={
{"Nloops", 1}};
char ReadLoop_usagehelp[]="Increasing address in big loop by reading and checking \n\
in it jumps.\n\
";

Tpardesc WriteLoop_parameters[1]={
{"Nloops", 1}};
char WriteLoop_usagehelp[]="Increasing address in big loop by writing reset and checking \n\
in it jumps.\n\
";

Tpardesc wvme_parameters[2]={
{"address", 2},
{"word", 2}};
char wvme_usagehelp[]="VME write. Use Pedja address.\n\
";

Tpardesc rvme_parameters[1]={
{"address", 2}};
char rvme_usagehelp[]="VME read.Use Pedja address.\n\
";

void GetStatusFPGA();
void MonitorLoad(int Ntimes, int Tscale);
void LoadFPGA();
void MonitorStatusFPGA(int Ntimes, int Tinterval);
void MonitorChange();
void GetStatusFM();
void ResetFM();
void LoadFM();
int ReadInputFile();
void CheckContent();
void EraseFM();
int Check1();
int ReadFlashMem();
int WriteFM(w32 address, w32 word);
int ReadFM(w32 address, int INCR);
int LoadFM0(int pat, int Nwords, int file);
int LoadFMErr(int pat, int Nwords, int file);
int Correct();
int LoadFMUB(int pat, int Nwords);
int Check0(int Nwords);
int Comb();
void Monitor(int Ntimes);
void VMEwrite(w32 Pedjaddress, int Ntimes, w32 word);
void ReadLoop(int Nloops);
void WriteLoop(int Nloops);
void wvme(w32 address, w32 word);
w32 rvme(w32 address);
void testcode();
void temp();
void testver();

int nnames=39;
Tname allnames[MAXNAMES]={
{"", tSYMNAME, NULL, (w32)BoardSpaceLength, 0.0, NULL, (w32)BoardBaseAddress, NULL},
{"CODE_ADD", tVMEADR, NULL, 0, 0.0, NULL, 0x4, NULL},
{"SERIAL_NUMBER", tVMEADR, NULL, 0, 0.0, NULL, 0x8, NULL},
{"VERSION_ADD", tVMEADR, NULL, 0, 0.0, NULL, 0xC, NULL},
{"SOFT_RESET", tVMEADR, NULL, 0, 0.0, NULL, 0x28, NULL},
{"TEMP_START", tVMEADR, NULL, 0, 0.0, NULL, 0x58, NULL},
{"TEMP_STATUS", tVMEADR, NULL, 0, 0.0, NULL, 0x5c, NULL},
{"TEMP_READ", tVMEADR, NULL, 0, 0.0, NULL, 0x60, NULL},
{"MonitLoad", tFUN, NULL, 0xdead, 0.0, NULL, 0, MonitLoad_usagehelp},
{"GetStatusFPGA", tFUN+0x400, (funcall)GetStatusFPGA, 0xdead, 0.0, NULL, 0, GetStatusFPGA_usagehelp},
{"MonitorLoad", tFUN+0x400, (funcall)MonitorLoad, 0xdead, 0.0, MonitorLoad_parameters, 2, MonitorLoad_usagehelp},
{"LoadFPGA", tFUN+0x400, (funcall)LoadFPGA, 0xdead, 0.0, NULL, 0, LoadFPGA_usagehelp},
{"MonitorStatusFPGA", tFUN+0x400, (funcall)MonitorStatusFPGA, 0xdead, 0.0, MonitorStatusFPGA_parameters, 2, MonitorStatusFPGA_usagehelp},
{"MonitorChange", tFUN+0x400, (funcall)MonitorChange, 0xdead, 0.0, NULL, 0, MonitorChange_usagehelp},
{"GetStatusFM", tFUN+0x400, (funcall)GetStatusFM, 0xdead, 0.0, NULL, 0, GetStatusFM_usagehelp},
{"ResetFM", tFUN+0x400, (funcall)ResetFM, 0xdead, 0.0, NULL, 0, ResetFM_usagehelp},
{"LoadFM", tFUN+0x400, (funcall)LoadFM, 0xdead, 0.0, NULL, 0, LoadFM_usagehelp},
{"ReadInputFile", tFUN+0x200, (funcall)ReadInputFile, 0xdead, 0.0, NULL, 0, ReadInputFile_usagehelp},
{"CheckContent", tFUN+0x400, (funcall)CheckContent, 0xdead, 0.0, NULL, 0, CheckContent_usagehelp},
{"EraseFM", tFUN+0x400, (funcall)EraseFM, 0xdead, 0.0, NULL, 0, EraseFM_usagehelp},
{"Check1", tFUN+0x200, (funcall)Check1, 0xdead, 0.0, NULL, 0, Check1_usagehelp},
{"ReadFlashMem", tFUN+0x200, (funcall)ReadFlashMem, 0xdead, 0.0, NULL, 0, NULL},
{"WriteFM", tFUN+0x200, (funcall)WriteFM, 0xdead, 0.0, WriteFM_parameters, 2, WriteFM_usagehelp},
{"ReadFM", tFUN+0x200, (funcall)ReadFM, 0xdead, 0.0, ReadFM_parameters, 2, ReadFM_usagehelp},
{"LoadFM0", tFUN+0x200, (funcall)LoadFM0, 0xdead, 0.0, LoadFM0_parameters, 3, LoadFM0_usagehelp},
{"LoadFMErr", tFUN+0x200, (funcall)LoadFMErr, 0xdead, 0.0, LoadFMErr_parameters, 3, LoadFMErr_usagehelp},
{"Correct", tFUN+0x200, (funcall)Correct, 0xdead, 0.0, NULL, 0, Correct_usagehelp},
{"LoadFMUB", tFUN+0x200, (funcall)LoadFMUB, 0xdead, 0.0, LoadFMUB_parameters, 2, LoadFMUB_usagehelp},
{"Check0", tFUN+0x200, (funcall)Check0, 0xdead, 0.0, Check0_parameters, 1, Check0_usagehelp},
{"Comb", tFUN+0x200, (funcall)Comb, 0xdead, 0.0, NULL, 0, NULL},
{"Monitor", tFUN+0x400, (funcall)Monitor, 0xdead, 0.0, Monitor_parameters, 1, Monitor_usagehelp},
{"VMEwrite", tFUN+0x400, (funcall)VMEwrite, 0xdead, 0.0, VMEwrite_parameters, 3, VMEwrite_usagehelp},
{"ReadLoop", tFUN+0x400, (funcall)ReadLoop, 0xdead, 0.0, ReadLoop_parameters, 1, ReadLoop_usagehelp},
{"WriteLoop", tFUN+0x400, (funcall)WriteLoop, 0xdead, 0.0, WriteLoop_parameters, 1, WriteLoop_usagehelp},
{"wvme", tFUN+0x400, (funcall)wvme, 0xdead, 0.0, wvme_parameters, 2, wvme_usagehelp},
{"rvme", tFUN+0x100, (funcall)rvme, 0xdead, 0.0, rvme_parameters, 1, rvme_usagehelp},
{"testcode", tFUN+0x400, (funcall)testcode, 0xdead, 0.0, NULL, 0, NULL},
{"temp", tFUN+0x400, (funcall)temp, 0xdead, 0.0, NULL, 0, NULL},
{"testver", tFUN+0x400, (funcall)testver, 0xdead, 0.0, NULL, 0, NULL}};
