/* generated by comp.py */
#include <stdio.h>
#include "vmewrap.h"
#include "lexan.h"
#include "vmeaistd.h"

char BoardName[]="lvdst";
char BoardBaseAddress[11]="0x810000";
char BoardSpaceLength[11]="0x800";
char BoardSpaceAddmod[11]="A24";
Tpardesc setOption_parameters[2]={
{"name", 3| 0x80000000},
{"value", 3| 0x80000000}};
char setOption_usagehelp[]="Set parameter name to value\n\
";

Tpardesc setTTCint_parameters[1]={
{"ttcint", 2}};
char setTTCint_usagehelp[]="Set 'L0 mode' :\n\
'L0 over fibre'         if ttcint is 8\n\
'L0 over cable'         if ttcint is 0\n\
\n\
This routine sets the TTC_INTERFACE register. It calculates\n\
2 least sifnificant bits (from BC_DELAY_ADD register). Bits 2..3 are\n\
taken from ttcint parameter.\n\
setTTCint() should be invoked ALWAYS AFTER BC_DELAY_ADD change.\n\
The 4 least significant bits of this register are used for setting:\n\
- 12.5ns delay for Orbit and/or L1\n\
- the polarity of L1 output      \n\
- 'L0 over TTC' mode\n\
\n\
TTC_INTERFACE bits:\n\
0  'Delay Orbit' flag. 0: no delay, 1: 12.5ns delay\n\
1  'Delay L1' flag. 0: no delay, 1: 12.5ns delay\n\
   Both bits depends on BC_DELAY_ADD.\n\
2   L1 polarity.    0: positive (TTCex, default)   1: negative (TTCvi)\n\
3  'L0 over TTC' flag. \n\
   0:  normal mode (only L1 as 1 bit over A-TTC channel)\n\
   1:  'L0overTTC' mode. In this mode: \n\
   - L0 is sent over coaxial cable as in normal mode. In addition,\n\
        it is sent over A-TTC channel as 2 bits '10' in 2 BC clocks\n\
   - L1 is sent as 2 bits '11' over A-TTCchannel\n\
";

char fpgainit_usagehelp[]="set BC_DELAY_ADD (0..31 in ns). setTTCint is activated after BC_DELAY_ADD\n\
written.\n\
";

char TTCinit_usagehelp[]="- initialise TTCvi for operation in STANDALONE mode\n\
- reset TTCrx over fibre (TTCrxready goes OFF for ~6ms)\n\
- set Control register 3 in TTCrx (over fibre), enabling Dout strobe \n\
- set FineDelay1,FineDelay2 and CoarseDelay TTCrx registers \n\
- send FEEreset (after more than 1 second)\n\
- check BUSY signal and print Warnings and/or Errors:\n\
  Warning: BUSY is ON before TTCrx reset\n\
  Error: BUSY not raised during 'TTCrx READY' off\n\
  Warning: BUSY not raised during 'QPLL LOCKED' off (if QPLL clock is used)\n\
  Error: BUSY ON 10milsecs after FEEreset\n\
";

Tpardesc TTCinitgs_parameters[2]={
{"stdalone", 1},
{"secs", 1}};
char TTCinitgs_usagehelp[]="- initialise TTCvi \n\
- reset TTCrx (over fibre)\n\
- set Control register 3 in TTCrx (over fibre), enabling Dout strobe\n\
Input: stdalone=1 if values valid for standalone are to be loaded\n\
                0 if global configuration is required \n\
       secs: number of seconds to wait till FEE becomes ready\n\
";

char printltuDefaults_usagehelp[]="Show shared memory content. Shared memory variables can be \n\
modified by Load from memory/Save buttons in Defaults editor.\n\
";

Tpardesc ttcPPdelay_parameters[1]={
{"bc", 1}};
char ttcPPdelay_usagehelp[]="Set Prepulse delay directly on TTCvi board. \n\
Warning: delay is set only on TTCviboard (i.e. it is not changed\n\
in memory, which means, TTCinit will set it back to value\n\
stored in shared memory (see Defaults editor)\n\
";

Tpardesc ttcDelays_parameters[3]={
{"Fine1ps", 1},
{"Fine2ps", 1},
{"Coarse", 1}};
char ttcDelays_usagehelp[]="Set delay registers directly in TTCrx, without resetting TTCrx.\n\
Input:\n\
Fine1ps, Fine2ps: required Fine delays on TTCrx chip in ps\n\
Coarse: the required content of TTCrx Coarse register\n\
";

char ttcFEEreset_usagehelp[]="-send 'Front End Electronics reset command' through TTC B-channel.\n\
 The header '0x8' is reserved for this command (e.g. 0x3 is allocated\n\
 for L2accept header).\n\
";

Tpardesc ttcFEEcmd_parameters[1]={
{"Command", 1}};
char ttcFEEcmd_usagehelp[]="-send 'Front End Electronics user defined command' through TTC B-channel.\n\
Command field: number 8-15 \n\
Command '8' is altready reserved for ttcFEEreset\n\
";

char ReadTemperature_usagehelp[]="returns temperature on the board in centigrades (-100 if error) ";

char measureBusy100ms_usagehelp[]="Return average busy time (busy/L0) during 100milsecs\n\
";

char measureBusy_usagehelp[]="Measure busy between 2 mouse clicks\n\
";

Tpardesc SLMsetstart_parameters[1]={
{"sel", 2}};
Tpardesc SLMswstart_parameters[2]={
{"n", 1},
{"milsecs", 1}};
Tpardesc ERenadis_parameters[1]={
{"enadis", 1}};
Tpardesc ERsetselector_parameters[1]={
{"selector", 2}};
Tpardesc ERdemand_parameters[1]={
{"demand", 2}};
Tpardesc SLMreadasci_parameters[2]={
{"filen", 3| 0x80000000},
{"slmdata", 2| 0x80000000}};
Tpardesc SLMload_parameters[1]={
{"filen", 3| 0x80000000}};
Tpardesc SLMwaitemuend_parameters[1]={
{"micsec", 1}};
Tpardesc setBUSY_parameters[1]={
{"binputs", 2}};
Tpardesc setAB_parameters[2]={
{"A", 2},
{"B", 2}};
Tpardesc SSMsetom_parameters[1]={
{"opmo", 2}};
Tpardesc SSMstartrec_parameters[1]={
{"mode", 2}};
Tpardesc SSMschedule_parameters[1]={
{"whenmode", 2}};
char ADC_Scan_usagehelp[]="Automatic synchronisation of CTP and LTU signal transitions. \n\
Before this measurement is started,\n\
arrange the following:\n\
- this LTU is in GLOBAL mode\n\
- L1 Data signal (CTP input connector) is continuously toggled\n\
  by BCclock frequency/2\n\
";

char ScopeAB_usagehelp[]="Signal selection for front panel \n\
A,B outputs\n\
";

char Counters_usagehelp[]="Counters monitor ";

Tpardesc getCounters_parameters[2]={
{"N", 1},
{"increments", 1}};
Tpardesc Tp_transition_parameters[1]={
{"print", 1}};
char Tp_transition_usagehelp[]=" \n\
Tp - Transition of the Synchronised Pattern Signal\n\
From here you will be able to make a ADC scan for the \n\
pattern signal. The pattern is setted to be TOGGLE. \n\
The aim of this function is to find something known \n\
as the exclusion zone of the BC_DELAY_ADD register. \n\
This zone correspond to the worst possible setting for that \n\
register. This is an hardware dependence constant.\n\
\n\
print option\n\
	0  --> Print some comments\n\
	1  --> Don't print anything\n\
\n\
 ";

char Ts_transition_usagehelp[]="\n\
Ts - The best setting for the BC_DELAY_ADD register\n\
 ";

Tpardesc D_pattern_delay_parameters[1]={
{"print", 1}};
char D_pattern_delay_usagehelp[]="\n\
For Pattern delay measurement. \n\
The aim of this function is to find the correct settings for the\n\
DELAY_1 register. This function uses the results from previous Syn functions.\n\
";

Tpardesc Find_Window_parameters[6]={
{"fromSetting", 1},
{"toSetting", 1},
{"seqType", 1},
{"runType", 1},
{"time", 1},
{"timeUnits", 3}};
char Find_Window_usagehelp[]="WindowFinding function.\n\
Delay done in Nano-seconds. We will start from the best possible point according \n\
to the cable. This value is obtained by the CableSignalSyn function.\n\
\n\
kFrom and kTo     this defind the measure range.\n\
		  A full test will be from kFrom=0 to kTo=31\n\
\n\
seqTpye \n\
	--> 1  for sequence pattern  0x800000\n\
	--> 2  for sequence patter   0xaaaaaa\n\
	--> 3  for random pattern\n\
\n\
runType \n\
	-->1    This correspond to a normal run (53 secs) \n\
		Type time=0 and timeUnits='n'\n\
        --> 0   Time and timeUnits defind by the user.\n\
                timeUnits   's' for seconds\n\
		  	    'h' for hours\n\
e.g. runType=0, time=1 and timeUnits='s' correspond to 1 sec run for each measure\n\
\n\
\n\
NOTE: To stop this program, please press CONTROL + X\n\
";

Tpardesc Find_History_parameters[4]={
{"fromSetting", 1},
{"toSetting", 1},
{"seqType", 1},
{"timeSteps", 1}};
char Find_History_usagehelp[]="findHistory function.\n\
Following up the previous measurement, i.e. the sampling window determination, this function\n\
reads the error counter in a regular interval of 1 minute. The idea here is to show whether \n\
the errors occurred in a burst or they were spread evenly over the entire period of measurement.\n\
\n\
kFrom and kTo     this defind the measure range.\n\
                  A full test will be from kFrom=0 to kTo=31\n\
\n\
seqTpye\n\
        --> 1  for sequence pattern  0x800000\n\
        --> 2  for sequence patter   0xaaaaaa\n\
        --> 3  for random pattern\n\
\n\
timeSteps is the entire period of measurement. If timeSteps is equal to 3,\n\
the measurement will last for 3 minutes.\n\
\n\
NOTE: To stop this program, please press CONTROL + X\n\
";

char TestLEDS_usagehelp[]="Click to Stop/Start blinking\n\
front panel LEDs\n\
  ";

char getSWLEDS_usagehelp[]="Print 1 line string xxxx\n\
where x is the status (0/1) of software LED word\n\
";

int setOption(char *name, char *value);
void setTTCint(w32 ttcint);
int fpgainit();
int TTCinit();
int TTCinitgs(int stdalone, int secs);
void printltuDefaults();
int ttcPPdelay(int bc);
int ttcDelays(int Fine1ps, int Fine2ps, int Coarse);
int ttcFEEreset();
int ttcFEEcmd(int Command);
int ReadTemperature();
int getgltuver();
int measureBusy100ms();
int measureBusy();
void SLMsetstart(w32 sel);
int SLMgetstart();
int SLMswstart(int n, int milsecs);
int SLMstart();
void ERenadis(int enadis);
void ERsetselector(w32 selector);
void ERdemand(w32 demand);
int SLMreadasci(char *filen, w32 *slmdata);
int SLMload(char *filen);
int SLMquit();
int SLMwaitemuend(int micsec);
void setBUSY(w32 binputs);
void setAB(w32 A, w32 B);
int SSMsetom(w32 opmo);
void SSMstartrec(w32 mode);
void SSMstoprec();
int SSMdump();
void SSMschedule(w32 whenmode);
int SSMclearac();
void SSMclear();
void getCounters(int N, int increments);
void clearCounters();
int Tp_transition(int print);
int Ts_transition();
int D_pattern_delay(int print);
void Find_Window(int fromSetting, int toSetting, int seqType, int runType, int time, char timeUnits);
void Find_History(int fromSetting, int toSetting, int seqType, int timeSteps);
void TestLEDS();
void getSWLEDS();

int nnames=164;
Tname allnames[MAXNAMES]={
{"lvdst", tSYMNAME, NULL, (w32)BoardSpaceLength, 0.0, NULL, (w32)BoardBaseAddress, NULL},
{"CODE_ADD", tVMEADR, NULL, 0, 0.0, NULL, 0x4, NULL},
{"SERIAL_NUMBER", tVMEADR, NULL, 0, 0.0, NULL, 0x8, NULL},
{"VERSION_ADD", tVMEADR, NULL, 0, 0.0, NULL, 0xC, NULL},
{"SOFT_RESET", tVMEADR, NULL, 0, 0.0, NULL, 0x28, NULL},
{"TEMP_START", tVMEADR, NULL, 0, 0.0, NULL, 0x58, NULL},
{"TEMP_STATUS", tVMEADR, NULL, 0, 0.0, NULL, 0x5c, NULL},
{"TEMP_READ", tVMEADR, NULL, 0, 0.0, NULL, 0x60, NULL},
{"MASTER_MODE", tVMEADR, NULL, 0, 0.0, NULL, 0x64, NULL},
{"LTUVERSION_ADD", tVMEADR, NULL, 0, 0.0, NULL, 0x80, NULL},
{"TEST_ADD", tVMEADR, NULL, 0, 0.0, NULL, 0xc0, NULL},
{"BC_STATUS", tVMEADR, NULL, 0, 0.0, NULL, 0xc4, NULL},
{"ADC_SELECT", tVMEADR, NULL, 0, 0.0, NULL, 0x4c0, NULL},
{"BC_DELAY_ADD", tVMEADR, NULL, 0, 0.0, NULL, 0x4c8, NULL},
{"ADC_START", tVMEADR, NULL, 0, 0.0, NULL, 0xcc, NULL},
{"ADC_DATA", tVMEADR, NULL, 0, 0.0, NULL, 0xd0, NULL},
{"ERROR_ENABLE", tVMEADR, NULL, 0, 0.0, NULL, 0xd4, NULL},
{"ERROR_STATUS", tVMEADR, NULL, 0, 0.0, NULL, 0xd8, NULL},
{"ERROR_SELECTOR", tVMEADR, NULL, 0, 0.0, NULL, 0xdc, NULL},
{"ERROR_DEMAND", tVMEADR, NULL, 0, 0.0, NULL, 0xe0, NULL},
{"ERROR_RATE", tVMEADR, NULL, 0, 0.0, NULL, 0x4e4, NULL},
{"ORBIT_CLEAR", tVMEADR, NULL, 0, 0.0, NULL, 0xe8, NULL},
{"EMULATION_START", tVMEADR, NULL, 0, 0.0, NULL, 0xec, NULL},
{"QUIT_SET", tVMEADR, NULL, 0, 0.0, NULL, 0xf0, NULL},
{"BREAK_SET", tVMEADR, NULL, 0, 0.0, NULL, 0xf4, NULL},
{"LAST_BC", tVMEADR, NULL, 0, 0.0, NULL, 0x4f8, NULL},
{"PREPULSE_BC", tVMEADR, NULL, 0, 0.0, NULL, 0x4fc, NULL},
{"CALIBRATION_BC", tVMEADR, NULL, 0, 0.0, NULL, 0x500, NULL},
{"GAP_BC", tVMEADR, NULL, 0, 0.0, NULL, 0x504, NULL},
{"ORBIT_BC", tVMEADR, NULL, 0, 0.0, NULL, 0x508, NULL},
{"L1_DELAY", tVMEADR, NULL, 0, 0.0, NULL, 0x50c, NULL},
{"L2_DELAY", tVMEADR, NULL, 0, 0.0, NULL, 0x510, NULL},
{"TRG_TOGGLE", tVMEADR, NULL, 0, 0.0, NULL, 0x5c4, NULL},
{"ORBIT_TIME", tVMEADR, NULL, 0, 0.0, NULL, 0x5c0, NULL},
{"PP_TIME", tVMEADR, NULL, 0, 0.0, NULL, 0x5c4, NULL},
{"TTC_DATA", tVMEADR, NULL, 0, 0.0, NULL, 0x5c8, NULL},
{"RATE_LIMIT", tVMEADR, NULL, 0, 0.0, NULL, 0x5cc, NULL},
{"SLM_ADD_CLEAR", tVMEADR, NULL, 0, 0.0, NULL, 0x114, NULL},
{"SLM_DATA", tVMEADR, NULL, 0, 0.0, NULL, 0x118, NULL},
{"EMU_STATUS", tVMEADR, NULL, 0, 0.0, NULL, 0x11c, NULL},
{"START_SET", tVMEADR, NULL, 0, 0.0, NULL, 0x520, NULL},
{"SOFT_TRIGGER", tVMEADR, NULL, 0, 0.0, NULL, 0x124, NULL},
{"RANDOM_NUMBER", tVMEADR, NULL, 0, 0.0, NULL, 0x528, NULL},
{"COUNT_PERIOD", tVMEADR, NULL, 0, 0.0, NULL, 0x52c, NULL},
{"TTC_INTERFACE", tVMEADR, NULL, 0, 0.0, NULL, 0x530, NULL},
{"STDALONE_MODE", tVMEADR, NULL, 0, 0.0, NULL, 0x534, NULL},
{"BUSY_ENABLE", tVMEADR, NULL, 0, 0.0, NULL, 0x138, NULL},
{"BUSY_STATUS", tVMEADR, NULL, 0, 0.0, NULL, 0x13c, NULL},
{"SW_BUSY", tVMEADR, NULL, 0, 0.0, NULL, 0x140, NULL},
{"L1_FORMAT", tVMEADR, NULL, 0, 0.0, NULL, 0x544, NULL},
{"L1MAX_CLEAR", tVMEADR, NULL, 0, 0.0, NULL, 0x148, NULL},
{"L2MAX_CLEAR", tVMEADR, NULL, 0, 0.0, NULL, 0x14c, NULL},
{"SCOPE_SELECT", tVMEADR, NULL, 0, 0.0, NULL, 0x550, NULL},
{"BACKPLANE_EN", tVMEADR, NULL, 0, 0.0, NULL, 0x554, NULL},
{"MINIMAX_SELECT", tVMEADR, NULL, 0, 0.0, NULL, 0x570, NULL},
{"MINIMAX_LIMIT", tVMEADR, NULL, 0, 0.0, NULL, 0x578, NULL},
{"FIFO_MAX", tVMEADR, NULL, 0, 0.0, NULL, 0x158, NULL},
{"SOFT_LED", tVMEADR, NULL, 0, 0.0, NULL, 0x15c, NULL},
{"BUSYMAX_DATA", tVMEADR, NULL, 0, 0.0, NULL, 0x168, NULL},
{"BUSYMINI_DATA", tVMEADR, NULL, 0, 0.0, NULL, 0x16c, NULL},
{"MINIMAX_CLEAR", tVMEADR, NULL, 0, 0.0, NULL, 0x174, NULL},
{"PIPELINE_CLEAR", tVMEADR, NULL, 0, 0.0, NULL, 0x198, NULL},
{"SSMcommand", tVMEADR, NULL, 0, 0.0, NULL, 0x19c, NULL},
{"SSMstart", tVMEADR, NULL, 0, 0.0, NULL, 0x1a0, NULL},
{"SSMstop", tVMEADR, NULL, 0, 0.0, NULL, 0x1a4, NULL},
{"SSMaddress", tVMEADR, NULL, 0, 0.0, NULL, 0x1a8, NULL},
{"SSMdata", tVMEADR, NULL, 0, 0.0, NULL, 0x1ac, NULL},
{"SSMstatus", tVMEADR, NULL, 0, 0.0, NULL, 0x1b0, NULL},
{"TIMING_TEST", tVMEADR, NULL, 0, 0.0, NULL, 0x1b8, NULL},
{"PLL_RESET", tVMEADR, NULL, 0, 0.0, NULL, 0x1bc, NULL},
{"TIMING_TEST", tVMEADR, NULL, 0, 0.0, NULL, 0x1b8, NULL},
{"TTC_STATUS", tVMEADR, NULL, 0, 0.0, NULL, 0x1c8, NULL},
{"COPYCOUNT", tVMEADR, NULL, 0, 0.0, NULL, 0x1d4, NULL},
{"COPYBUSY", tVMEADR, NULL, 0, 0.0, NULL, 0x1d8, NULL},
{"COPYCLEARADD", tVMEADR, NULL, 0, 0.0, NULL, 0x1dc, NULL},
{"COPYREAD", tVMEADR, NULL, 0, 0.0, NULL, 0x1e0, NULL},
{"CLEARCOUNTER", tVMEADR, NULL, 0, 0.0, NULL, 0x5ac, NULL},
{"CODE_ADD", tVMEADR, NULL, 0, 0.0, NULL, 0x4, NULL},
{"SERIAL_NUMBER", tVMEADR, NULL, 0, 0.0, NULL, 0x8, NULL},
{"VERSION_ADD", tVMEADR, NULL, 0, 0.0, NULL, 0xC, NULL},
{"SOFT_RESET", tVMEADR, NULL, 0, 0.0, NULL, 0x28, NULL},
{"TEMP_START", tVMEADR, NULL, 0, 0.0, NULL, 0x58, NULL},
{"TEMP_STATUS", tVMEADR, NULL, 0, 0.0, NULL, 0x5c, NULL},
{"TEMP_READ", tVMEADR, NULL, 0, 0.0, NULL, 0x60, NULL},
{"MASTER_MODE", tVMEADR, NULL, 0, 0.0, NULL, 0x64, NULL},
{"LTUVERSION_ADD", tVMEADR, NULL, 0, 0.0, NULL, 0x80, NULL},
{"TEST_ADD", tVMEADR, NULL, 0, 0.0, NULL, 0xc0, NULL},
{"BC_STATUS", tVMEADR, NULL, 0, 0.0, NULL, 0xc4, NULL},
{"BC_DELAY_ADD", tVMEADR, NULL, 0, 0.0, NULL, 0x4c8, NULL},
{"ADC_START", tVMEADR, NULL, 0, 0.0, NULL, 0xcc, NULL},
{"ADC_DATA", tVMEADR, NULL, 0, 0.0, NULL, 0xd0, NULL},
{"SCOPE_SELECT", tVMEADR, NULL, 0, 0.0, NULL, 0x550, NULL},
{"SOFT_LED", tVMEADR, NULL, 0, 0.0, NULL, 0x15c, NULL},
{"SSMcommand", tVMEADR, NULL, 0, 0.0, NULL, 0x19c, NULL},
{"SSMstart", tVMEADR, NULL, 0, 0.0, NULL, 0x1a0, NULL},
{"SSMstop", tVMEADR, NULL, 0, 0.0, NULL, 0x1a4, NULL},
{"SSMaddress", tVMEADR, NULL, 0, 0.0, NULL, 0x1a8, NULL},
{"SSMdata", tVMEADR, NULL, 0, 0.0, NULL, 0x1ac, NULL},
{"SSMstatus", tVMEADR, NULL, 0, 0.0, NULL, 0x1b0, NULL},
{"PLL_RESET", tVMEADR, NULL, 0, 0.0, NULL, 0x1bc, NULL},
{"COPYCOUNT", tVMEADR, NULL, 0, 0.0, NULL, 0x1d4, NULL},
{"COPYBUSY", tVMEADR, NULL, 0, 0.0, NULL, 0x1d8, NULL},
{"COPYCLEARADD", tVMEADR, NULL, 0, 0.0, NULL, 0x1dc, NULL},
{"COPYREAD", tVMEADR, NULL, 0, 0.0, NULL, 0x1e0, NULL},
{"CLEARCOUNTER", tVMEADR, NULL, 0, 0.0, NULL, 0x5ac, NULL},
{"ADC_SELECT", tVMEADR, NULL, 0, 0.0, NULL, 0x480, NULL},
{"PATTERN_SEL", tVMEADR, NULL, 0, 0.0, NULL, 0x484, NULL},
{"SEQ_PERIOD", tVMEADR, NULL, 0, 0.0, NULL, 0x488, NULL},
{"SEQ_DATA", tVMEADR, NULL, 0, 0.0, NULL, 0x48c, NULL},
{"RANDOM_RATE", tVMEADR, NULL, 0, 0.0, NULL, 0x490, NULL},
{"SYN_EDGE", tVMEADR, NULL, 0, 0.0, NULL, 0x494, NULL},
{"DELAY_1", tVMEADR, NULL, 0, 0.0, NULL, 0x498, NULL},
{"DELAY_2", tVMEADR, NULL, 0, 0.0, NULL, 0x49c, NULL},
{"CLEAR_ERR1", tVMEADR, NULL, 0, 0.0, NULL, 0x4a0, NULL},
{"CLEAR_ERR2", tVMEADR, NULL, 0, 0.0, NULL, 0x4a4, NULL},
{"ERROR_STATUS", tVMEADR, NULL, 0, 0.0, NULL, 0x200, NULL},
{"setOption", tFUN+0x200, (funcall)setOption, 0xdead, 0.0, setOption_parameters, 2, setOption_usagehelp},
{"setTTCint", tFUN+0x400, (funcall)setTTCint, 0xdead, 0.0, setTTCint_parameters, 1, setTTCint_usagehelp},
{"fpgainit", tFUN+0x200, (funcall)fpgainit, 0xdead, 0.0, NULL, 0, fpgainit_usagehelp},
{"TTCinit", tFUN+0x200, (funcall)TTCinit, 0xdead, 0.0, NULL, 0, TTCinit_usagehelp},
{"TTCinitgs", tFUN+0x200, (funcall)TTCinitgs, 0xdead, 0.0, TTCinitgs_parameters, 2, TTCinitgs_usagehelp},
{"printltuDefaults", tFUN+0x400, (funcall)printltuDefaults, 0xdead, 0.0, NULL, 0, printltuDefaults_usagehelp},
{"ttcPPdelay", tFUN+0x200, (funcall)ttcPPdelay, 0xdead, 0.0, ttcPPdelay_parameters, 1, ttcPPdelay_usagehelp},
{"ttcDelays", tFUN+0x200, (funcall)ttcDelays, 0xdead, 0.0, ttcDelays_parameters, 3, ttcDelays_usagehelp},
{"ttcFEEreset", tFUN+0x200, (funcall)ttcFEEreset, 0xdead, 0.0, NULL, 0, ttcFEEreset_usagehelp},
{"ttcFEEcmd", tFUN+0x200, (funcall)ttcFEEcmd, 0xdead, 0.0, ttcFEEcmd_parameters, 1, ttcFEEcmd_usagehelp},
{"setGLOBAL", tFUN, NULL, 0xdead, 0.0, NULL, 0, NULL},
{"setSTDALONE", tFUN, NULL, 0xdead, 0.0, NULL, 0, NULL},
{"ReadTemperature", tFUN+0x200, (funcall)ReadTemperature, 0xdead, 0.0, NULL, 0, ReadTemperature_usagehelp},
{"getgltuver", tFUN+0x200, (funcall)getgltuver, 0xdead, 0.0, NULL, 0, NULL},
{"measureBusy100ms", tFUN+0x200, (funcall)measureBusy100ms, 0xdead, 0.0, NULL, 0, measureBusy100ms_usagehelp},
{"measureBusy", tFUN+0x200, (funcall)measureBusy, 0xdead, 0.0, NULL, 0, measureBusy_usagehelp},
{"SLMsetstart", tFUN+0x400, (funcall)SLMsetstart, 0xdead, 0.0, SLMsetstart_parameters, 1, NULL},
{"SLMgetstart", tFUN+0x200, (funcall)SLMgetstart, 0xdead, 0.0, NULL, 0, NULL},
{"SLMswstart", tFUN+0x200, (funcall)SLMswstart, 0xdead, 0.0, SLMswstart_parameters, 2, NULL},
{"SLMstart", tFUN+0x200, (funcall)SLMstart, 0xdead, 0.0, NULL, 0, NULL},
{"ERenadis", tFUN+0x400, (funcall)ERenadis, 0xdead, 0.0, ERenadis_parameters, 1, NULL},
{"ERsetselector", tFUN+0x400, (funcall)ERsetselector, 0xdead, 0.0, ERsetselector_parameters, 1, NULL},
{"ERdemand", tFUN+0x400, (funcall)ERdemand, 0xdead, 0.0, ERdemand_parameters, 1, NULL},
{"SLMreadasci", tFUN+0x200, (funcall)SLMreadasci, 0xdead, 0.0, SLMreadasci_parameters, 2, NULL},
{"SLMload", tFUN+0x200, (funcall)SLMload, 0xdead, 0.0, SLMload_parameters, 1, NULL},
{"SLMquit", tFUN+0x200, (funcall)SLMquit, 0xdead, 0.0, NULL, 0, NULL},
{"SLMwaitemuend", tFUN+0x200, (funcall)SLMwaitemuend, 0xdead, 0.0, SLMwaitemuend_parameters, 1, NULL},
{"setBUSY", tFUN+0x400, (funcall)setBUSY, 0xdead, 0.0, setBUSY_parameters, 1, NULL},
{"setAB", tFUN+0x400, (funcall)setAB, 0xdead, 0.0, setAB_parameters, 2, NULL},
{"SSMsetom", tFUN+0x200, (funcall)SSMsetom, 0xdead, 0.0, SSMsetom_parameters, 1, NULL},
{"SSMstartrec", tFUN+0x400, (funcall)SSMstartrec, 0xdead, 0.0, SSMstartrec_parameters, 1, NULL},
{"SSMstoprec", tFUN+0x400, (funcall)SSMstoprec, 0xdead, 0.0, NULL, 0, NULL},
{"SSMdump", tFUN+0x200, (funcall)SSMdump, 0xdead, 0.0, NULL, 0, NULL},
{"SSMschedule", tFUN+0x400, (funcall)SSMschedule, 0xdead, 0.0, SSMschedule_parameters, 1, NULL},
{"SSMclearac", tFUN+0x200, (funcall)SSMclearac, 0xdead, 0.0, NULL, 0, NULL},
{"SSMclear", tFUN+0x400, (funcall)SSMclear, 0xdead, 0.0, NULL, 0, NULL},
{"ADC_Scan", tFUN, NULL, 0xdead, 0.0, NULL, 0, ADC_Scan_usagehelp},
{"ScopeAB", tFUN, NULL, 0xdead, 0.0, NULL, 0, ScopeAB_usagehelp},
{"Counters", tFUN, NULL, 0xdead, 0.0, NULL, 0, Counters_usagehelp},
{"getCounters", tFUN+0x400, (funcall)getCounters, 0xdead, 0.0, getCounters_parameters, 2, NULL},
{"clearCounters", tFUN+0x400, (funcall)clearCounters, 0xdead, 0.0, NULL, 0, NULL},
{"Tp_transition", tFUN+0x200, (funcall)Tp_transition, 0xdead, 0.0, Tp_transition_parameters, 1, Tp_transition_usagehelp},
{"Ts_transition", tFUN+0x200, (funcall)Ts_transition, 0xdead, 0.0, NULL, 0, Ts_transition_usagehelp},
{"D_pattern_delay", tFUN+0x200, (funcall)D_pattern_delay, 0xdead, 0.0, D_pattern_delay_parameters, 1, D_pattern_delay_usagehelp},
{"Find_Window", tFUN+0x400, (funcall)Find_Window, 0xdead, 0.0, Find_Window_parameters, 6, Find_Window_usagehelp},
{"Find_History", tFUN+0x400, (funcall)Find_History, 0xdead, 0.0, Find_History_parameters, 4, Find_History_usagehelp},
{"TestLEDS", tFUN+0x400, (funcall)TestLEDS, 0xdead, 0.0, NULL, 0, TestLEDS_usagehelp},
{"getSWLEDS", tFUN+0x400, (funcall)getSWLEDS, 0xdead, 0.0, NULL, 0, getSWLEDS_usagehelp}};
