/* generated by comp.py */
#include <stdio.h>
#include "vmewrap.h"
#include "lexan.h"
#include "vmeaistd.h"

char BoardName[]="bobr";
char BoardBaseAddress[11]="0xb00000";
char BoardSpaceLength[11]="0x14000";
char BoardSpaceAddmod[11]="A24";
Tpardesc readBSTpp_parameters[2]={
{"bstn", 1},
{"nppmax", 1}};
char readBSTpp_usagehelp[]="wait for LHCpp + read BST message. \n\
bstn: 1:BST1   2:BST2\n\
nppmax: max. number of PP to wait for\n\
";

Tpardesc readBSTprint_parameters[1]={
{"bstn", 1}};
Tpardesc readBSTutcturn_parameters[1]={
{"ut", 3}};
char readBSTutcturn_usagehelp[]="Input:\n\
  ut: 'u' ->detect 'UTC change'\n\
  ut: 't' ->detect 'Turn change'\n\
Operation (CPU/UTC times given in 'secs micsecs'):\n\
read UTC1 and CPU1 time, addyTurnCount, BlockTurnCount\n\
while 1:\n\
  read UTC2 time, BlockTurnCount2\n\
  if (UTC2!=UTC1) or (BlockTurnCount2!=BlockTurnCount): \n\
    read CPU2; break\n\
  ix++;\n\
print CPU/UTC 1, addyTurnCount, BlockTurnCount, ut\n\
      CPU/UTC 2, addyTurnCount, BlockTurnCount2, ix\n\
";

void readBSTpp(int bstn, int nppmax);
void readBSTprint(int bstn);
void readBST1raw();
void readBSTutcturn(char ut);
void readall();

int nnames=25;
Tname allnames[MAXNAMES]={
{"bobr", tSYMNAME, NULL, (w32)BoardSpaceLength, 0.0, NULL, (w32)BoardBaseAddress, NULL},
{"MessageInput", tVMEADR, NULL, 0, 0.0, NULL, 0x0800, NULL},
{"addyTime0", tVMEADR, NULL, 0, 0.0, NULL, 0x0800, NULL},
{"addyTime1", tVMEADR, NULL, 0, 0.0, NULL, 0x0804, NULL},
{"addyTurnCount", tVMEADR, NULL, 0, 0.0, NULL, 0x0808, NULL},
{"AuxMessageInput", tVMEADR, NULL, 0, 0.0, NULL, 0x0c00, NULL},
{"BlockIdentificator", tVMEADR, NULL, 0, 0.0, NULL, 0x00, NULL},
{"addyVMEIRQVector", tVMEADR, NULL, 0, 0.0, NULL, 0x08, NULL},
{"BlockStatus", tVMEADR, NULL, 0, 0.0, NULL, 0x10, NULL},
{"addyCoarseDelay", tVMEADR, NULL, 0, 0.0, NULL, 0x14, NULL},
{"addyHWByteSelect", tVMEADR, NULL, 0, 0.0, NULL, 0x18, NULL},
{"addyHWByteOutp", tVMEADR, NULL, 0, 0.0, NULL, 0x1c, NULL},
{"addyBunchSelectOutpEnable", tVMEADR, NULL, 0, 0.0, NULL, 0x20, NULL},
{"addyBunchSelectOutpEnableSubAddr", tVMEADR, NULL, 0, 0.0, NULL, 0x24, NULL},
{"addyIRQByteAddrSelect", tVMEADR, NULL, 0, 0.0, NULL, 0x30, NULL},
{"addyIRQByteAddrMask", tVMEADR, NULL, 0, 0.0, NULL, 0x34, NULL},
{"addyTTCErrorSingle", tVMEADR, NULL, 0, 0.0, NULL, 0x40, NULL},
{"addyTTCErrorDouble", tVMEADR, NULL, 0, 0.0, NULL, 0x44, NULL},
{"addyTTCErrorReady", tVMEADR, NULL, 0, 0.0, NULL, 0x48, NULL},
{"BlockTurnCount", tVMEADR, NULL, 0, 0.0, NULL, 0x50, NULL},
{"readBSTpp", tFUN+0x400, (funcall)readBSTpp, 0xdead, 0.0, readBSTpp_parameters, 2, readBSTpp_usagehelp},
{"readBSTprint", tFUN+0x400, (funcall)readBSTprint, 0xdead, 0.0, readBSTprint_parameters, 1, NULL},
{"readBST1raw", tFUN+0x400, (funcall)readBST1raw, 0xdead, 0.0, NULL, 0, NULL},
{"readBSTutcturn", tFUN+0x400, (funcall)readBSTutcturn, 0xdead, 0.0, readBSTutcturn_parameters, 1, readBSTutcturn_usagehelp},
{"readall", tFUN+0x400, (funcall)readall, 0xdead, 0.0, NULL, 0, NULL}};
