/* generated by comp.py */
#include <stdio.h>
#include "vmewrap.h"
#include "lexan.h"
#include "vmeaistd.h"

char BoardName[]="fanio";
char BoardBaseAddress[11]="0xc00000";
char BoardSpaceLength[11]="0x200";
char BoardSpaceAddmod[11]="A24";
Tpardesc setdelay_parameters[2]={
{"channel", 1},
{"delay", 1}};
char setdelay_usagehelp[]="Input: \n\
channel: number 0-23   or    24: set the dealy for all the channels\n\
delay: delay in ns, value for delay register willl be \n\
       calculated: value= delay/12.5 \n\
Operation:\n\
- set Bit [2] of CONTROL_REG (ClockPhaseEnabled)  to 1 !\n\
- set channel(s)\n\
";

char scan_usagehelp[]="FANOUT scan.\n\
Input: Common fanout input is connected to L0 source.\n\
Operation:\n\
measure number of L0 triggers for 4 phases\n\
1st measurement:\n\
scan()\n\
phase: 0 L0s: 176075\n\
phase: 1 L0s: 176111\n\
phase: 2 L0s: 176111\n\
phase: 3 L0s: 176111\n\
scan()\n\
phase: 0 L0s: 176068\n\
phase: 1 L0s: 176111\n\
phase: 2 L0s: 176117\n\
phase: 3 L0s: 176105\n\
\n\
clock delayed by 3 ns:\n\
phase: 0 L0s: 139155\n\
phase: 1 L0s: 176111\n\
phase: 2 L0s: 177135\n\
phase: 3 L0s: 176111\n\
scan()\n\
phase: 0 L0s: 171364\n\
phase: 1 L0s: 176147\n\
phase: 2 L0s: 176075\n\
phase: 3 L0s: 176111\n\
";

void setdelay(int channel, int delay);
void scan();

int nnames=38;
Tname allnames[MAXNAMES]={
{"fanio", tSYMNAME, NULL, (w32)BoardSpaceLength, 0.0, NULL, (w32)BoardBaseAddress, NULL},
{"VME_RESET", tVMEADR, NULL, 0, 0.0, NULL, 0x10, NULL},
{"VERSION_NUMBER", tVMEADR, NULL, 0, 0.0, NULL, 0x20, NULL},
{"ENABLE_RECEIVER", tVMEADR, NULL, 0, 0.0, NULL, 0x30, NULL},
{"DELAY0", tVMEADR, NULL, 0, 0.0, NULL, 0x40, NULL},
{"DELAY1", tVMEADR, NULL, 0, 0.0, NULL, 0x50, NULL},
{"DELAY2", tVMEADR, NULL, 0, 0.0, NULL, 0x60, NULL},
{"DELAY3", tVMEADR, NULL, 0, 0.0, NULL, 0x70, NULL},
{"DELAY4", tVMEADR, NULL, 0, 0.0, NULL, 0x80, NULL},
{"DELAY5", tVMEADR, NULL, 0, 0.0, NULL, 0x90, NULL},
{"DELAY6", tVMEADR, NULL, 0, 0.0, NULL, 0xa0, NULL},
{"DELAY7", tVMEADR, NULL, 0, 0.0, NULL, 0xb0, NULL},
{"DELAY8", tVMEADR, NULL, 0, 0.0, NULL, 0xc0, NULL},
{"DELAY9", tVMEADR, NULL, 0, 0.0, NULL, 0xd0, NULL},
{"DELAY10", tVMEADR, NULL, 0, 0.0, NULL, 0xe0, NULL},
{"DELAY11", tVMEADR, NULL, 0, 0.0, NULL, 0xf0, NULL},
{"DELAY12", tVMEADR, NULL, 0, 0.0, NULL, 0x100, NULL},
{"DELAY13", tVMEADR, NULL, 0, 0.0, NULL, 0x110, NULL},
{"DELAY14", tVMEADR, NULL, 0, 0.0, NULL, 0x120, NULL},
{"DELAY15", tVMEADR, NULL, 0, 0.0, NULL, 0x130, NULL},
{"DELAY16", tVMEADR, NULL, 0, 0.0, NULL, 0x140, NULL},
{"DELAY17", tVMEADR, NULL, 0, 0.0, NULL, 0x150, NULL},
{"DELAY18", tVMEADR, NULL, 0, 0.0, NULL, 0x160, NULL},
{"DELAY19", tVMEADR, NULL, 0, 0.0, NULL, 0x170, NULL},
{"DELAY20", tVMEADR, NULL, 0, 0.0, NULL, 0x180, NULL},
{"DELAY21", tVMEADR, NULL, 0, 0.0, NULL, 0x190, NULL},
{"DELAY22", tVMEADR, NULL, 0, 0.0, NULL, 0x1a0, NULL},
{"DELAY23", tVMEADR, NULL, 0, 0.0, NULL, 0x1b0, NULL},
{"CONTROL_REG", tVMEADR, NULL, 0, 0.0, NULL, 0x1c0, NULL},
{"BUSY_MASK", tVMEADR, NULL, 0, 0.0, NULL, 0x1d0, NULL},
{"L0_COUNTER", tVMEADR, NULL, 0, 0.0, NULL, 0x1e0, NULL},
{"READ_INPUTS", tVMEADR, NULL, 0, 0.0, NULL, 0x1f0, NULL},
{"c0_counter", tVMEADR, NULL, 0, 0.0, NULL, 0x200, NULL},
{"c1_counter", tVMEADR, NULL, 0, 0.0, NULL, 0x210, NULL},
{"c2_counter", tVMEADR, NULL, 0, 0.0, NULL, 0x220, NULL},
{"c3_counter", tVMEADR, NULL, 0, 0.0, NULL, 0x230, NULL},
{"setdelay", tFUN+0x400, (funcall)setdelay, 0xdead, 0.0, setdelay_parameters, 2, setdelay_usagehelp},
{"scan", tFUN+0x400, (funcall)scan, 0xdead, 0.0, NULL, 0, scan_usagehelp}};
