/* generated by comp.py */
#include <stdio.h>
#include "vmewrap.h"
#include "lexan.h"
#include "vmeaistd.h"

char BoardName[]="switch";
char BoardBaseAddress[11]="0x110000";
char BoardSpaceLength[11]="0x30068";
char BoardSpaceAddmod[11]="A24";
char check_usagehelp[]="read CSR from all switch boards\n\
";

Tpardesc setchanctpltu_parameters[3]={
{"ctpltu", 1},
{"input", 1},
{"output", 1}};
char setchanctpltu_usagehelp[]="ctpltu: 1:ctp   0:ltu\n\
input: 0 disable channel output\n\
       1..50 connect output to input\n\
output: 1..25   \n\
RC: 0: already set or error (no vme write)\n\
    1: set (vme write)\n\
";

Tpardesc showcfgCPU_parameters[1]={
{"ctpltu", 1}};
char showcfgCPU_usagehelp[]="ctpltu: 1:ctp   0:ltu\n\
Print current configuration (only connected outputs)\n\
inp -> ctpinp   where:\n\
inp -the nmber of CTPSWITCH input (1..50)\n\
ctpinp -the number of CTP L0 input +1  (2..25)\n\
";

Tpardesc setCounters_parameters[1]={
{"type", 1}};
char setCounters_usagehelp[]="set type of pulses to be counted:\n\
0: counting off (default)\n\
5: <  1 period\n\
6: >= 1 period\n\
7: == 1 period\n\
0xa: >= 2 periods\n\
0xb: == 2 periods\n\
0xe: >= 3 periods\n\
0xf level ON (probably means: strobing with clock? \n\
";

char printCounters_usagehelp[]="Print all input counters (both RX boards)\n\
";

Tpardesc loadTable_parameters[1]={
{"ctpltu", 1}};
char loadTable_usagehelp[]="ctpltu:   1 for ctp   or 0 for ltu. Load config file:\n\
CTP.SWITCH ctp switch \n\
LTU.SWITCH ltu switch \n\
Return:\n\
rc: 0: ok, loaded\n\
";

void reset();
void check();
int setchanctpltu(int ctpltu, int input, int output);
void showcfgCPU(int ctpltu);
void setCounters(int type);
void printCounters();
int loadTable(int ctpltu);

int nnames=11;
Tname allnames[MAXNAMES]={
{"switch", tSYMNAME, NULL, (w32)BoardSpaceLength, 0.0, NULL, (w32)BoardBaseAddress, NULL},
{"CSR", tVMEADR, NULL, 0, 0.0, NULL, 0x0, NULL},
{"TXCFGSTART", tVMEADR, NULL, 0, 0.0, NULL, 0x4, NULL},
{"RXCNTSTART", tVMEADR, NULL, 0, 0.0, NULL, 0x4, NULL},
{"reset", tFUN+0x400, (funcall)reset, 0xdead, 0.0, NULL, 0, NULL},
{"check", tFUN+0x400, (funcall)check, 0xdead, 0.0, NULL, 0, check_usagehelp},
{"setchanctpltu", tFUN+0x200, (funcall)setchanctpltu, 0xdead, 0.0, setchanctpltu_parameters, 3, setchanctpltu_usagehelp},
{"showcfgCPU", tFUN+0x400, (funcall)showcfgCPU, 0xdead, 0.0, showcfgCPU_parameters, 1, showcfgCPU_usagehelp},
{"setCounters", tFUN+0x400, (funcall)setCounters, 0xdead, 0.0, setCounters_parameters, 1, setCounters_usagehelp},
{"printCounters", tFUN+0x400, (funcall)printCounters, 0xdead, 0.0, NULL, 0, printCounters_usagehelp},
{"loadTable", tFUN+0x200, (funcall)loadTable, 0xdead, 0.0, loadTable_parameters, 1, loadTable_usagehelp}};
