/* generated by comp.py */
#include <stdio.h>
#include "vmewrap.h"
#include "lexan.h"
#include "vmeaistd.h"

char BoardName[]="corde";
char BoardBaseAddress[11]="0x7000000";
char BoardSpaceLength[11]="0x7fc00";
char BoardSpaceAddmod[11]="A32";
Tpardesc set_step_parameters[4]={
{"step_ps", 1},
{"ministep_ps", 1},
{"sleep_us", 1},
{"sign", 1}};
char set_step_usagehelp[]="Define 1 step. Step is time delay (in ps), set in CORDE board\n\
by increasing/decreasing delay in ministeps by successive VME writes.\n\
The time between 2 successive writes is set by sleep_us.\n\
step_ps: step in ps\n\
ministep_ps: ministep delay in ps \n\
sleep_us: in microsecs. Meaningfull values: 0, >20\n\
sign: 0 - positive, 1 - negative\n\
";

char reset_usagehelp[]="reset Corde board: writing 1 and 0 to RESET register.\n\
";

char readall_usagehelp[]="read all delay registers.\n\
";

Tpardesc set_parameters[2]={
{"delay", 1},
{"ps", 1}};
char set_usagehelp[]="set delay to ps\n\
delay: register to be changed\n\
1: ORBMAIN     4:BCMAIN       7:BC1\n\
2:ORB2         5:BCREF\n\
3:ORB1         6:BC2\n\
\n\
ps: \n\
0     0x0     -5120ps\n\
5120  0x200       0ps\n\
10230 0x3ff   +5110ps\n\
";

Tpardesc up_parameters[2]={
{"delay", 1},
{"ms", 1}};
char up_usagehelp[]="Increase successively delay by defined step/ministep (see set_step). \n\
Allow ms miliseconds between steps.\n\
delay: register to be changed\n\
1:ORBMAIN \n\
2:ORB2 \n\
3:ORB1 \n\
4:BCMAIN \n\
5:BCREF \n\
6:BC2 \n\
7:BC1\n\
";

void set_step(int step_ps, int ministep_ps, int sleep_us, int sign);
void reset();
void readall();
void set(int delay, int ps);
void up(int delay, int ms);

int nnames=8;
Tname allnames[MAXNAMES]={
{"corde", tSYMNAME, NULL, (w32)BoardSpaceLength, 0.0, NULL, (w32)BoardBaseAddress, NULL},
{"RESET", tVMEADR, NULL, 0, 0.0, NULL, 0x24, NULL},
{"ORBMAIN", tVMEADR, NULL, 0, 0.0, NULL, 0x7fbb4, NULL},
{"set_step", tFUN+0x400, (funcall)set_step, 0xdead, 0.0, set_step_parameters, 4, set_step_usagehelp},
{"reset", tFUN+0x400, (funcall)reset, 0xdead, 0.0, NULL, 0, reset_usagehelp},
{"readall", tFUN+0x400, (funcall)readall, 0xdead, 0.0, NULL, 0, readall_usagehelp},
{"set", tFUN+0x400, (funcall)set, 0xdead, 0.0, set_parameters, 2, set_usagehelp},
{"up", tFUN+0x400, (funcall)up, 0xdead, 0.0, up_parameters, 2, up_usagehelp}};
