/* generated by comp.py */
#include <stdio.h>
#include "vmewrap.h"
#include "lexan.h"
#include "vmeaistd.h"

char BoardName[]="rfrx";
char BoardBaseAddress[11]="0x400000";
char BoardSpaceLength[11]="0x100";
char BoardSpaceAddmod[11]="A24";
char writeall_usagehelp[]="- set RF board (0x5 for BC and 0x70 for Orbit)\n\
";

char readall_usagehelp[]="ch1_ref:0x5\n\
ch2_ref:0x5\n\
ch3_ref:0x70\n\
";

void writeall();
void readall();

int nnames=11;
Tname allnames[MAXNAMES]={
{"rfrx", tSYMNAME, NULL, (w32)BoardSpaceLength, 0.0, NULL, (w32)BoardBaseAddress, NULL},
{"ch1_ref", tVMEADR|0x04000000, NULL, 0, 0.0, NULL, 0x12, NULL},
{"ch2_ref", tVMEADR|0x04000000, NULL, 0, 0.0, NULL, 0x14, NULL},
{"ch3_ref", tVMEADR|0x04000000, NULL, 0, 0.0, NULL, 0x16, NULL},
{"ch1_freq_low", tVMEADR|0x04000000, NULL, 0, 0.0, NULL, 0x18, NULL},
{"ch1_freq_high", tVMEADR|0x04000000, NULL, 0, 0.0, NULL, 0x1a, NULL},
{"ident_id", tVMEADR|0x04000000, NULL, 0, 0.0, NULL, 0x8, NULL},
{"card_id", tVMEADR|0x04000000, NULL, 0, 0.0, NULL, 0x24, NULL},
{"board_id", tVMEADR|0x04000000, NULL, 0, 0.0, NULL, 0x3a, NULL},
{"writeall", tFUN+0x400, (funcall)writeall, 0xdead, 0.0, NULL, 0, writeall_usagehelp},
{"readall", tFUN+0x400, (funcall)readall, 0xdead, 0.0, NULL, 0, readall_usagehelp}};
