cp VALID.CTPINPUTS.ARXIV/VALID.CTPINPUTS.BEFORE_CHANGING_NAMING_SCHEME VALID.CTPINPUTS
cp CTP.SWITCH.ARXIV/CTP.SWITCH.BEFORE_CHANGING_NAMING_SCHEME CTP.SWITCH
cp L0.INPUTS.ARXIV/L0.INPUTS.BEFORE_CHANGING_NAMING_SCHEME L0.INPUTS