/* generated by comp.py */
#include <stdio.h>
#include "vmewrap.h"
#include "lexan.h"
#include "vmeaistd.h"

char BoardName[]="simple";
char BoardBaseAddress[11]="0x829000";
char BoardSpaceLength[11]="0xd000";
char BoardSpaceAddmod[11]="A24";
Tpardesc vmeloop_parameters[4]={
{"address", 2},
{"loops", 1},
{"value", 2},
{"mics", 1}};
char vmeloop_usagehelp[]="address: rel. adress (4, 8, 12,... for 32 bits words readings)\n\
loops: 0: endless loop\n\
value: 0: read + print\n\
       1: read only\n\
      >1: write, no print\n\
mics: mics between vme reads/writes. 0: do not wait between vme r/w\n\
";

void vmeloop(w32 address, int loops, w32 value, int mics);

int nnames=6;
Tname allnames[MAXNAMES]={
{"simple", tSYMNAME, NULL, {0}, 0.0, NULL, {0}, NULL},
{"CODE_ADD", tVMEADR, NULL, {0}, 0.0, NULL, {0x4}, NULL},
{"SERIAL_NUMBER", tVMEADR, NULL, {0}, 0.0, NULL, {0x8}, NULL},
{"VMEVERSION_ADD", tVMEADR, NULL, {0}, 0.0, NULL, {0xc}, NULL},
{"FPGAVERSION_ADD", tVMEADR, NULL, {0}, 0.0, NULL, {0x80}, NULL},
{"vmeloop", tFUN+0x400, (funcall)vmeloop, {0xdead}, 0.0, vmeloop_parameters, {4}, vmeloop_usagehelp}};
