/* generated by comp.py */
#include <stdio.h>
#include "vmewrap.h"
#include "lexan.h"
#include "vmeaistd.h"

char BoardName[]="ttcmi";
char BoardBaseAddress[11]="0xf00000";
char BoardSpaceLength[11]="0x100000";
char BoardSpaceAddmod[11]="A32";
Tpardesc read1000_parameters[2]={
{"fifoadr", 2},
{"del", 1}};
char read1000_usagehelp[]="fifoadr: addr. of ORB1_PERIOD_FIFO_RD\n\
";

Tpardesc calibrate_parameters[3]={
{"orb", 1},
{"fromdel", 1},
{"todel", 1}};
char calibrate_usagehelp[]="orb:\n\
0: ORB1/BC1 -BPTX monitoring\n\
1: ORB2/BC2 -\n\
2: ORBmain=ORB1 BCmain= BC1   ALICE clock BEAM1\n\
4: ORBmain=ORB2 BCmain= BC2   ALICE clock BEAM2\n\
\n\
Set BC_DELAY25_BC1/2/MAIN to their final values before using this!\n\
16.3.2011:\n\
all 3 Set to 29,28,27 - ORB1/BC1 calibration is not working\n\
    for <=26 is OK\n\
Similarly for ORB2/BC2: with BC_DELAY25_BC2>27 calibration is not working\n\
(i.e. all read1000() returns >0 )\n\
Here is the table with 0 in BC_DELAY25_BC1/2/main:\n\
   bad regions[ns]\n\
0:  9-9.5    (# of bad readings in region: <5)\n\
1: 21.5-22    detto\n\
2: 8.5-9.5   <90\n\
\n\
i2cset_delay -removed DLL resync, now ok:\n\
Here is the table with 29 in BC_DELAY25_BC1/2/main:\n\
   bad regions[ns]\n\
0:  24        (# of bad readings in region: <=1)\n\
1:  10        16   \n\
2:  24        1  (when BC1corde changed 8500->8650 then 100 bad readings)\n\
4:  10.5      1\n\
";

Tpardesc i2cset_delay_parameters[2]={
{"delayadd", 2},
{"halfns", 1}};
char i2cset_delay_usagehelp[]="set delayadd with halfns value (in steps of 0.5 ns):\n\
#define BC_DELAY25_BC1             0x7D000\n\
#define BC_DELAY25_BC2             0x7D004\n\
#define BC_DELAY25_BCREF           0x7D008\n\
#define BC_DELAY25_BCMAIN          0x7D00C\n\
#define BC_DELAY25_GCR             0x7D014\n\
#define ORBIN_DELAY25_ORB1         0x7D020\n\
#define ORBIN_DELAY25_ORB2         0x7D024\n\
#define ORBIN_DELAY25_GCR          0x7D034\n\
#define ORBOUT_DELAY25_ORB1        0x7D040\n\
#define ORBOUT_DELAY25_ORB2        0x7D044\n\
#define ORBOUT_DELAY25_ORBMAIN     0x7D048\n\
#define ORBOUT_DELAY25_GCR         0x7D054\n\
";

char printBC_DELAYS_usagehelp[]="read BC_DEALY25_* registers\n\
";

Tpardesc setOrbitCoarse_parameters[2]={
{"addr", 2},
{"coarse", 1}};
char setOrbitCoarse_usagehelp[]="#define ORB1_COARSE_DELAY          0x7FB5C\n\
#define ORB2_COARSE_DELAY          0x7FB1C\n\
#define ORBmain_COARSE_DELAY       0x7FADC\n\
";

Tpardesc setbcorbitMain_parameters[1]={
{"maino", 1}};
char setbcorbitMain_usagehelp[]="Input: maino: \n\
1 -> BC1/Orbit1\n\
2 -> BC2/Orbit2\n\
3 -> BCref/int BCmain synch. orbit generator\n\
4 -> internal 40.078MHz/int BCmain synch. orbit generator\n\
Output:\n\
- clock is changed + log messages written into DAQ infoLogger\n\
Note (todo?):\n\
BCREF/\n\
localBC/\n\
";

Tpardesc resetQPLL_parameters[1]={
{"chip", 1}};
char resetQPLL_usagehelp[]="chip:\n\
0: Delay25 chips\n\
1: no efect\n\
2: BC1-QPLL chip\n\
2: BC2-QPLL chip\n\
2: BCref-QPLL chip\n\
2: BCmain-QPLL chip\n\
6: TTCrx chips\n\
7: whole board\n\
Operation:\n\
1. read+print BSET word\n\
set BSET bit\n\
2. read+print BSET word\n\
set BCLEAR bit\n\
3. read+print BSET word\n\
";

char resyncDLL_usagehelp[]="resync DEALY25 chip (write 0x40 -> BC_DELAY25_GCR)\n\
";

Tpardesc setorbitdelay_parameters[1]={
{"bcs", 1}};
char setorbitdelay_usagehelp[]="Set orbit delay in BCs in 3 ORBX_COARSE_DELAY registers.\n\
0    - minimum shift\n\
3563 -maximum allowed shift\n\
4000 - show current setting\n\
";

char readorbitcnts_usagehelp[]="Read and print ORBX_COUNTER (X: main 2 1) registers ";

char writeall_usagehelp[]="- reset CORDE board\n\
- set RF boards (0x5 for BC and 0x70 for Orbit)\n\
- set polarity/length for all 3 RF2TTC outputs: MAIN/ORB2/ORB1\n\
- set BC1/2 and Orbit1/2 delays\n\
";

char readall_usagehelp[]="PROGRAM_ID:8102008\n\
ch1_ref:0x5\n\
ch2_ref:0x5\n\
ch3_ref:0x70\n\
rc:0 vsp:1\n\
ch1_ref:0x5\n\
ch2_ref:0x5\n\
ch3_ref:0x70\n\
polarity0: 0x7fae0:0x1   0x7fad8 0x26 delay:0\n\
polarity1: 0x7fb20:0x1   0x7fb18 0x26 delay:0\n\
polarity2: 0x7fb60:0x1   0x7fb58 0x26 delay:0\n\
WORKING_MODE (bits 0..6 (0:man,1:auto)for: BC1/2/r/main Orb1/2/m:0 \n\
BST_Machine_Mode:7\n\
BC 1/2/ref selection (Int/Ext):EEE\n\
BC/ORB main_MAN_SELECT: 0 2\n\
BCmain_MAN_SELECT:\n\
0:40.078MHz int clock, 1: BCref, 2: BC2in, 3: BC1in\n\
ORBmain_MAN_SELECT:\n\
0:Orbit1, 1:Orbit2, 2:int BCmain sync. orbit generator\n\
";

char monitorstatus_usagehelp[]="used for measurement at the end of 2008.\n\
";

char readstatus_usagehelp[]="read QPLL* and TTCrx status bits.\n\
RC: 0xTAB\n\
T: bit 8. 1: TTCrx ok\n\
A: [7..6] BC1 error,locked (i.e. 01 correct)\n\
   [5..4] BC2\n\
B: [3..2] BCref\n\
   [1..0] BCmain\n\
I.e. 0x155 is correct status of all 9 bits\n\
     0x1aa error in both BC, was not locked. NEXT READING is 0x155 !\n\
";

Tpardesc getCounter_parameters[3]={
{"board", 1},
{"reladr", 1},
{"customer", 1}};
Tpardesc getCounters_parameters[3]={
{"N", 1},
{"accrual", 1},
{"customer", 1}};
Tpardesc clearCounters_parameters[1]={
{"customer", 1}};
char l0AB_usagehelp[]="rc: 0: if L0 borad firmware >0xAB\n\
    boardversion if firmware <=0xAB \n\
";

Tpardesc DAQonoff_parameters[1]={
{"daqon", 1}};
char DAQonoff_usagehelp[]="daqon:0       ->daq active\n\
daqon:0xb     ->daq off (i.e. produce triggers in spite of DDL red diode \n\
                on INT board is on \n\
daqon: other  -> show current status.\n\
NOTE about LEDs on INT board:\n\
DDL interface: \n\
  green:DDL line ready, data not read out \n\
  flashing green: DDL line ready, data are read out\n\
  flashing orange: data are read out, backpressure is sometimes active\n\
                   (DAQ is not able to read everything)\n\
upper DDL LED on INT board fron panel:\n\
  red: INT is raising CTPBUSY on backlplane, because of full DDL buffers\n\
INT_DDL_EMU word in normal mode (i.e. DAQ active):\n\
     DDLfiLF  DDLfiBEN  DDLfiDIR\n\
0x20:      0         1         0  data can't be sent (DDL not enabled from DIU)\n\
0x30:      0         1         1  data sent\n\
0x70:      1         1         1  data not sent (backpressure)\n\
";

int read1000(w32 fifoadr, int del);
void calibrate(int orb, int fromdel, int todel);
void i2cset_delay(w32 delayadd, int halfns);
void printBC_DELAYS();
void setOrbitCoarse(w32 addr, int coarse);
void setbcorbitMain(int maino);
void resetQPLL(int chip);
void resyncDLL();
void setorbitdelay(int bcs);
void readorbitcnts();
void writeall();
void readall();
void monitorstatus();
w32 readstatus();
w32 getCounter(int board, int reladr, int customer);
void getCounters(int N, int accrual, int customer);
void clearCounters(int customer);
int l0AB();
void DAQonoff(int daqon);

int nnames=76;
Tname allnames[MAXNAMES]={
{"ttcmi", tSYMNAME, NULL, (w32)BoardSpaceLength, 0.0, NULL, (w32)BoardBaseAddress, NULL},
{"ch1_ref", tVMEADR|0x04000000, NULL, 0, 0.0, NULL, 0x12, NULL},
{"ch2_ref", tVMEADR|0x04000000, NULL, 0, 0.0, NULL, 0x14, NULL},
{"ch3_ref", tVMEADR|0x04000000, NULL, 0, 0.0, NULL, 0x16, NULL},
{"ch1_freq_low", tVMEADR|0x04000000, NULL, 0, 0.0, NULL, 0x18, NULL},
{"ch1_freq_high", tVMEADR|0x04000000, NULL, 0, 0.0, NULL, 0x1a, NULL},
{"ident_id", tVMEADR|0x04000000, NULL, 0, 0.0, NULL, 0x8, NULL},
{"card_id", tVMEADR|0x04000000, NULL, 0, 0.0, NULL, 0x24, NULL},
{"board_id", tVMEADR|0x04000000, NULL, 0, 0.0, NULL, 0x3a, NULL},
{"BSET", tVMEADR, NULL, 0, 0.0, NULL, 0x10, NULL},
{"BCLEAR", tVMEADR, NULL, 0, 0.0, NULL, 0x14, NULL},
{"PROGRAM_ID", tVMEADR, NULL, 0, 0.0, NULL, 0xc, NULL},
{"WORKING_MODE", tVMEADR, NULL, 0, 0.0, NULL, 0x7fa78, NULL},
{"BST_Machine_Mode", tVMEADR, NULL, 0, 0.0, NULL, 0x7fa9c, NULL},
{"TTCrx_status", tVMEADR, NULL, 0, 0.0, NULL, 0x7faa0, NULL},
{"BC1_QPLL_STATUS", tVMEADR, NULL, 0, 0.0, NULL, 0x7fbe8, NULL},
{"BC2_QPLL_STATUS", tVMEADR, NULL, 0, 0.0, NULL, 0x7fbb8, NULL},
{"BCref_QPLL_STATUS", tVMEADR, NULL, 0, 0.0, NULL, 0x7fb98, NULL},
{"BCmain_QPLL_STATUS", tVMEADR, NULL, 0, 0.0, NULL, 0x7fb7c, NULL},
{"BC1_QPLL_MODE", tVMEADR, NULL, 0, 0.0, NULL, 0x7fbf0, NULL},
{"BC2_QPLL_MODE", tVMEADR, NULL, 0, 0.0, NULL, 0x7fbc0, NULL},
{"BCref_QPLL_MODE", tVMEADR, NULL, 0, 0.0, NULL, 0x7fba0, NULL},
{"BCmain_QPLL_MODE", tVMEADR, NULL, 0, 0.0, NULL, 0x7fb80, NULL},
{"ORBX_COUNTER", tVMEADR, NULL, 0, 0.0, NULL, 0x7facc, NULL},
{"ORBX_POLARITY", tVMEADR, NULL, 0, 0.0, NULL, 0x7fae0, NULL},
{"ORBX_LENGTH", tVMEADR, NULL, 0, 0.0, NULL, 0x7fad8, NULL},
{"ORBX_COARSE_DELAY", tVMEADR, NULL, 0, 0.0, NULL, 0x7fadc, NULL},
{"BC1_MAN_SELECT", tVMEADR, NULL, 0, 0.0, NULL, 0x7fbfc, NULL},
{"BC2_MAN_SELECT", tVMEADR, NULL, 0, 0.0, NULL, 0x7fbcc, NULL},
{"BCref_MAN_SELECT", tVMEADR, NULL, 0, 0.0, NULL, 0x7fbac, NULL},
{"BCmain_MAN_SELECT", tVMEADR, NULL, 0, 0.0, NULL, 0x7fb8c, NULL},
{"ORBmain_MAN_SELECT", tVMEADR, NULL, 0, 0.0, NULL, 0x7faec, NULL},
{"ORB1_MAN_SELECT", tVMEADR, NULL, 0, 0.0, NULL, 0x7fb6c, NULL},
{"ORB2_MAN_SELECT", tVMEADR, NULL, 0, 0.0, NULL, 0x7fb2c, NULL},
{"BC_DELAY25_BC1", tVMEADR, NULL, 0, 0.0, NULL, 0x7D000, NULL},
{"BC_DELAY25_BC2", tVMEADR, NULL, 0, 0.0, NULL, 0x7D004, NULL},
{"BC_DELAY25_BCREF", tVMEADR, NULL, 0, 0.0, NULL, 0x7D008, NULL},
{"BC_DELAY25_BCMAIN", tVMEADR, NULL, 0, 0.0, NULL, 0x7D00C, NULL},
{"BC_DELAY25_GCR", tVMEADR, NULL, 0, 0.0, NULL, 0x7D014, NULL},
{"ORBIN_DELAY25_ORB1", tVMEADR, NULL, 0, 0.0, NULL, 0x7D020, NULL},
{"ORBIN_DELAY25_ORB2", tVMEADR, NULL, 0, 0.0, NULL, 0x7D024, NULL},
{"ORBIN_DELAY25_GCR", tVMEADR, NULL, 0, 0.0, NULL, 0x7D034, NULL},
{"ORBOUT_DELAY25_ORB1", tVMEADR, NULL, 0, 0.0, NULL, 0x7D040, NULL},
{"ORBOUT_DELAY25_ORB2", tVMEADR, NULL, 0, 0.0, NULL, 0x7D044, NULL},
{"ORBOUT_DELAY25_ORBMAIN", tVMEADR, NULL, 0, 0.0, NULL, 0x7D048, NULL},
{"ORBOUT_DELAY25_GCR", tVMEADR, NULL, 0, 0.0, NULL, 0x7D054, NULL},
{"DELAY25_REG", tVMEADR, NULL, 0, 0.0, NULL, 0x7D200, NULL},
{"PERIOD_COUNTER_RESET", tVMEADR, NULL, 0, 0.0, NULL, 0x7FA48, NULL},
{"PERIOD_COUNTER_ENABLE", tVMEADR, NULL, 0, 0.0, NULL, 0x7FA64, NULL},
{"ORB2_DAC", tVMEADR, NULL, 0, 0.0, NULL, 0x7FAFC, NULL},
{"ORB1_DAC", tVMEADR, NULL, 0, 0.0, NULL, 0x7FB3C, NULL},
{"ORB1_PERIOD_FIFO_RD", tVMEADR, NULL, 0, 0.0, NULL, 0x7FB40, NULL},
{"ORB2_PERIOD_FIFO_RD", tVMEADR, NULL, 0, 0.0, NULL, 0x7FB00, NULL},
{"ORBmain_PERIOD_FIFO_RD", tVMEADR, NULL, 0, 0.0, NULL, 0x7FAC0, NULL},
{"ORB1_COARSE_DELAY", tVMEADR, NULL, 0, 0.0, NULL, 0x7FB5C, NULL},
{"ORB2_COARSE_DELAY", tVMEADR, NULL, 0, 0.0, NULL, 0x7FB1C, NULL},
{"ORBmain_COARSE_DELAY", tVMEADR, NULL, 0, 0.0, NULL, 0x7FADC, NULL},
{"read1000", tFUN+0x200, (funcall)read1000, 0xdead, 0.0, read1000_parameters, 2, read1000_usagehelp},
{"calibrate", tFUN+0x400, (funcall)calibrate, 0xdead, 0.0, calibrate_parameters, 3, calibrate_usagehelp},
{"i2cset_delay", tFUN+0x400, (funcall)i2cset_delay, 0xdead, 0.0, i2cset_delay_parameters, 2, i2cset_delay_usagehelp},
{"printBC_DELAYS", tFUN+0x400, (funcall)printBC_DELAYS, 0xdead, 0.0, NULL, 0, printBC_DELAYS_usagehelp},
{"setOrbitCoarse", tFUN+0x400, (funcall)setOrbitCoarse, 0xdead, 0.0, setOrbitCoarse_parameters, 2, setOrbitCoarse_usagehelp},
{"setbcorbitMain", tFUN+0x400, (funcall)setbcorbitMain, 0xdead, 0.0, setbcorbitMain_parameters, 1, setbcorbitMain_usagehelp},
{"resetQPLL", tFUN+0x400, (funcall)resetQPLL, 0xdead, 0.0, resetQPLL_parameters, 1, resetQPLL_usagehelp},
{"resyncDLL", tFUN+0x400, (funcall)resyncDLL, 0xdead, 0.0, NULL, 0, resyncDLL_usagehelp},
{"setorbitdelay", tFUN+0x400, (funcall)setorbitdelay, 0xdead, 0.0, setorbitdelay_parameters, 1, setorbitdelay_usagehelp},
{"readorbitcnts", tFUN+0x400, (funcall)readorbitcnts, 0xdead, 0.0, NULL, 0, readorbitcnts_usagehelp},
{"writeall", tFUN+0x400, (funcall)writeall, 0xdead, 0.0, NULL, 0, writeall_usagehelp},
{"readall", tFUN+0x400, (funcall)readall, 0xdead, 0.0, NULL, 0, readall_usagehelp},
{"monitorstatus", tFUN+0x400, (funcall)monitorstatus, 0xdead, 0.0, NULL, 0, monitorstatus_usagehelp},
{"readstatus", tFUN+0x100, (funcall)readstatus, 0xdead, 0.0, NULL, 0, readstatus_usagehelp},
{"getCounter", tFUN+0x100, (funcall)getCounter, 0xdead, 0.0, getCounter_parameters, 3, NULL},
{"getCounters", tFUN+0x400, (funcall)getCounters, 0xdead, 0.0, getCounters_parameters, 3, NULL},
{"clearCounters", tFUN+0x400, (funcall)clearCounters, 0xdead, 0.0, clearCounters_parameters, 1, NULL},
{"l0AB", tFUN+0x200, (funcall)l0AB, 0xdead, 0.0, NULL, 0, l0AB_usagehelp},
{"DAQonoff", tFUN+0x400, (funcall)DAQonoff, 0xdead, 0.0, DAQonoff_parameters, 1, DAQonoff_usagehelp}};
